# https://esphome.io/components/tca9548a
tca9548a:
  - address: 0x70
    id: tca9548a_multiplex0
    i2c_id: i2c1_bus
    channels:
      - bus_id: tca9548a_multiplex0_channel0
        channel: 0
#      - bus_id: tca9548a_multiplex0_channel1
#        channel: 1
#      - bus_id: tca9548a_multiplex0_channel2
#        channel: 2
#      [...]