sensor:
  - platform: ct_clamp
    sensor: ${ct_clamp_name}_adc_sensor_${ct_clamp_sufix}
    name: ${name}_${ct_clamp_name}_${ct_clamp_sufix}
    accuracy_decimals: 3
    update_interval: ${ct_clamp_update_interval}
    filters:
      - calibrate_linear:
         method: exact
         datapoints:
          - 0 -> 0.00
          - 0.09 -> 3.478260869565217
          - 0.19 -> 6.956521739130435
          - 0.29 -> 10.43478260869565

  # https://esphome.io/components/sensor/ads1115
  - platform: ads1115
    ads1115_id: ${ct_clamp_ads1115_hub}
    #name: "Measured voltage"
    multiplexer: ${ct_clamp_multiplexer}
    gain: ${ct_clamp_gain}
    id: ${ct_clamp_name}_adc_sensor_${ct_clamp_sufix}
    accuracy_decimals: 3
    update_interval: ${ct_clamp_update_interval} # Defaults to 60s.